# All Vagrant configuration is done below. 
Vagrant.configure("2") do |config|


  # Every Vagrant development environment requires a box. 
   config.vm.box = "hashicorp/bionic64"
  
  # Create a forwarded port 
   config.vm.network "forwarded_port", guest: 80, host: 80
   config.vm.network "forwarded_port", guest: 443, host: 443

  # Create a public network
   config.vm.network "public_network", ip: "192.168.1.41"

  # Synced folder mapping
   config.vm.synced_folder "./docker", "/home/vagrant/docker/", create: true
  
  # Resource provisioning
   config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
     vb.memory = "2048"
     vb.cpus = 1
   end
  
  # Shell scripts
   config.vm.provision "shell", path: "install.sh"
end
